#!/bin/bash

while getopts ":i:o:w:h" opt; do
  case $opt in
    i) input_file="$OPTARG"
    ;;
    o) output_file="$OPTARG"
    ;;
    w) width="$OPTARG"
    ;;
    h) height="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done